# Generated by Django 5.1.5 on 2025-03-02 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(null=True)),
                ('contact_infor', models.CharField(max_length=15)),
                ('service_selection', models.CharField(choices=[('home_cleaning', 'Home_cleaning'), ('office_cleaning', 'Office_cleaning'), ('maintanance', 'Maintanance'), ('maid_placement', 'Maid_Placement')], default='home_cleaning', max_length=20)),
                ('location_infor', models.CharField(max_length=100)),
                ('additional_details', models.CharField(blank=True, max_length=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
